services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - DB_TYPE=${DB_TYPE}
                - DB_URL=${DB_URL}
                - DB_USER=${DB_USER}
                - DB_PASSWORD=${DB_PASSWORD}
        depends_on:
            db_postgres:
                condition: service_healthy
        ports:
            - "8080:8080"

    db_postgres:
        image: postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./initdb:/docker-entrypoint-initdb.d  # Mount the initialization scripts
        environment:
            POSTGRES_DB: postgres
            POSTGRES_HOST_AUTH_METHOD: trust
        ports:
            - "5432:5432"
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 1s
            retries: 30

volumes:
    pgdata: